package com.kilha.www.vo.logistics;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.type.IntegerTypeHandler;

/**
 * â�� ���̺� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Warehouse implements Serializable {

   /** serialVersionUID. */
   private static final long serialVersionUID = 1L;

   /** â���ڵ�. */
   private Integer warehouseCode;

   /** â���. */
   private String warehouseName;

   /** â������. */
   private String warehouseType;

   /**
    * ������.
    */
   public Warehouse() {
   }

   /**
    * â���ڵ��� �����մϴ�..
    * 
    * @param warehouseCode
    *            â���ڵ�
    */
   public void setWarehouseCode(Integer warehouseCode) {
      this.warehouseCode = warehouseCode;
   }

   /**
    * â���ڵ��� �����ɴϴ�..
    * 
    * @return â���ڵ�
    */
   public Integer getWarehouseCode() {
      return this.warehouseCode;
   }

   /**
    * â����� �����մϴ�..
    * 
    * @param warehouseName
    *            â���
    */
   public void setWarehouseName(String warehouseName) {
      this.warehouseName = warehouseName;
   }

   /**
    * â����� �����ɴϴ�..
    * 
    * @return â���
    */
   public String getWarehouseName() {
      return this.warehouseName;
   }

   /**
    * â�������� �����մϴ�..
    * 
    * @param warehouseType
    *            â������
    */
   public void setWarehouseType(String warehouseType) {
      this.warehouseType = warehouseType;
   }

   /**
    * â�������� �����ɴϴ�..
    * 
    * @return â������
    */
   public String getWarehouseType() {
      return this.warehouseType;
   }


   /**
    * {@inheritDoc}
    */
   @Override
   public int hashCode() {
      final int prime = 31;
      int result = 1;
      result = prime * result + ((warehouseCode == null) ? 0 : warehouseCode.hashCode());
      return result;
   }

   /**
    * {@inheritDoc}
    */
   @Override
   public boolean equals(Object obj) {
      if (this == obj) {
         return true;
      }
      if (obj == null) {
         return false;
      }
      if (getClass() != obj.getClass()) {
         return false;
      }
      Warehouse other = (Warehouse) obj;
      if (warehouseCode == null) {
         if (other.warehouseCode != null) {
            return false;
         }
      } else if (!warehouseCode.equals(other.warehouseCode)) {
         return false;
      }
      return true;
   }

   @Override
   public String toString() {
      return "Warehouse [warehouseCode=" + warehouseCode + ", warehouseName=" + warehouseName + ", warehouseType="
            + warehouseType + "]";
   }
}
   
