package com.kilha.www.vo;
import java.io.Serializable;

/**
 * 주소 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Address implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 우편번호. */
	private String addressPost;

	/** 시, 도 구분. */
	private String addressDetail1;

	/** 구, 군 구분. */
	private String addressDetail2;

	/** 지번, 도로명 주소. */
	private String addressDetail3;

	/** 나머지 상세주소. */
	private String addressDetail4;
	
	/** 매장코드. */
	private Integer shopCode;
	
	/**
	 * 생성자.
	 */
	public Address() {
	}

	/**
	 * 우편번호을 설정합니다..
	 * 
	 * @param addressPost
	 *            우편번호
	 */
	public void setAddressPost(String addressPost) {
		this.addressPost = addressPost;
	}

	/**
	 * 우편번호을 가져옵니다..
	 * 
	 * @return 우편번호
	 */
	public String getAddressPost() {
		return this.addressPost;
	}

	/**
	 * 시, 도 구분을 설정합니다..
	 * 
	 * @param addressDetail1
	 *            시, 도 구분
	 */
	public void setAddressDetail1(String addressDetail1) {
		this.addressDetail1 = addressDetail1;
	}

	/**
	 * 시, 도 구분을 가져옵니다..
	 * 
	 * @return 시, 도 구분
	 */
	public String getAddressDetail1() {
		return this.addressDetail1;
	}

	/**
	 * 구, 군 구분을 설정합니다..
	 * 
	 * @param addressDetail2
	 *            구, 군 구분
	 */
	public void setAddressDetail2(String addressDetail2) {
		this.addressDetail2 = addressDetail2;
	}

	/**
	 * 구, 군 구분을 가져옵니다..
	 * 
	 * @return 구, 군 구분
	 */
	public String getAddressDetail2() {
		return this.addressDetail2;
	}

	/**
	 * 지번, 도로명 주소을 설정합니다..
	 * 
	 * @param addressDetail3
	 *            지번, 도로명 주소
	 */
	public void setAddressDetail3(String addressDetail3) {
		this.addressDetail3 = addressDetail3;
	}

	/**
	 * 지번, 도로명 주소을 가져옵니다..
	 * 
	 * @return 지번, 도로명 주소
	 */
	public String getAddressDetail3() {
		return this.addressDetail3;
	}

	/**
	 * 나머지 상세주소을 설정합니다..
	 * 
	 * @param addressDetail4
	 *            나머지 상세주소
	 */
	public void setAddressDetail4(String addressDetail4) {
		this.addressDetail4 = addressDetail4;
	}

	/**
	 * 나머지 상세주소을 가져옵니다..
	 * 
	 * @return 나머지 상세주소
	 */
	public String getAddressDetail4() {
		return this.addressDetail4;
	}


	public Integer getShopCode() {
		return shopCode;
	}

	public void setShopCode(Integer shopCode) {
		this.shopCode = shopCode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addressPost == null) ? 0 : addressPost.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Address other = (Address) obj;
		if (addressPost == null) {
			if (other.addressPost != null) {
				return false;
			}
		} else if (!addressPost.equals(other.addressPost)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Address [addressPost=" + addressPost + ", addressDetail1=" + addressDetail1 + ", addressDetail2="
				+ addressDetail2 + ", addressDetail3=" + addressDetail3 + ", addressDetail4=" + addressDetail4
				+ ", shopCode=" + shopCode + "]";
	}
	
	
}
