package com.kilha.www.vo;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 경쟁사 정보 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Competitor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 경쟁사코드. */
	private Short competitorCode;

	/** 경쟁사 명. */
	private String competitorName;

	/** 경쟁사 납품 정보 테이블 목록. */
	private Set<Competitorsupply> competitorsupplySet;

	/**
	 * 생성자.
	 */
	public Competitor() {
		this.competitorsupplySet = new HashSet<Competitorsupply>();
	}

	/**
	 * 경쟁사코드을 설정합니다..
	 * 
	 * @param competitorCode
	 *            경쟁사코드
	 */
	public void setCompetitorCode(Short competitorCode) {
		this.competitorCode = competitorCode;
	}

	/**
	 * 경쟁사코드을 가져옵니다..
	 * 
	 * @return 경쟁사코드
	 */
	public Short getCompetitorCode() {
		return this.competitorCode;
	}

	/**
	 * 경쟁사 명을 설정합니다..
	 * 
	 * @param competitorName
	 *            경쟁사 명
	 */
	public void setCompetitorName(String competitorName) {
		this.competitorName = competitorName;
	}

	/**
	 * 경쟁사 명을 가져옵니다..
	 * 
	 * @return 경쟁사 명
	 */
	public String getCompetitorName() {
		return this.competitorName;
	}

	/**
	 * 경쟁사 납품 정보 테이블 목록을 설정합니다..
	 * 
	 * @param competitorsupplySet
	 *            경쟁사 납품 정보 테이블 목록
	 */
	public void setCompetitorsupplySet(Set<Competitorsupply> competitorsupplySet) {
		this.competitorsupplySet = competitorsupplySet;
	}

	/**
	 * 경쟁사 납품 정보 테이블를 추가합니다..
	 * 
	 * @param competitorsupply
	 *            경쟁사 납품 정보 테이블
	 */
	public void addCompetitorsupply(Competitorsupply competitorsupply) {
		this.competitorsupplySet.add(competitorsupply);
	}

	/**
	 * 경쟁사 납품 정보 테이블 목록을 가져옵니다..
	 * 
	 * @return 경쟁사 납품 정보 테이블 목록
	 */
	public Set<Competitorsupply> getCompetitorsupplySet() {
		return this.competitorsupplySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((competitorCode == null) ? 0 : competitorCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Competitor other = (Competitor) obj;
		if (competitorCode == null) {
			if (other.competitorCode != null) {
				return false;
			}
		} else if (!competitorCode.equals(other.competitorCode)) {
			return false;
		}
		return true;
	}

}
