package com.kilha.www.vo;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 부서테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Department implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 부서코드. */
	private Short depCode;

	/** 부서명. */
	private String depName;

	/** 직원테이블 목록. */
	private Set<Staff> staffSet;

	/**
	 * 생성자.
	 */
	public Department() {
		this.staffSet = new HashSet<Staff>();
	}

	/**
	 * 부서코드을 설정합니다..
	 * 
	 * @param depCode
	 *            부서코드
	 */
	public void setDepCode(Short depCode) {
		this.depCode = depCode;
	}

	/**
	 * 부서코드을 가져옵니다..
	 * 
	 * @return 부서코드
	 */
	public Short getDepCode() {
		return this.depCode;
	}

	/**
	 * 부서명을 설정합니다..
	 * 
	 * @param depName
	 *            부서명
	 */
	public void setDepName(String depName) {
		this.depName = depName;
	}

	/**
	 * 부서명을 가져옵니다..
	 * 
	 * @return 부서명
	 */
	public String getDepName() {
		return this.depName;
	}

	/**
	 * 직원테이블 목록을 설정합니다..
	 * 
	 * @param staffSet
	 *            직원테이블 목록
	 */
	public void setStaffSet(Set<Staff> staffSet) {
		this.staffSet = staffSet;
	}

	/**
	 * 직원테이블를 추가합니다..
	 * 
	 * @param staff
	 *            직원테이블
	 */
	public void addStaff(Staff staff) {
		this.staffSet.add(staff);
	}

	/**
	 * 직원테이블 목록을 가져옵니다..
	 * 
	 * @return 직원테이블 목록
	 */
	public Set<Staff> getStaffSet() {
		return this.staffSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((depCode == null) ? 0 : depCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Department other = (Department) obj;
		if (depCode == null) {
			if (other.depCode != null) {
				return false;
			}
		} else if (!depCode.equals(other.depCode)) {
			return false;
		}
		return true;
	}

}
