package com.kilha.www.vo;
import java.io.Serializable;
import java.util.Date;

/**
 * KPI테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Kpi implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** kpi 코드. */
	private Integer kpiCode;

	/** 액수. */
	private Integer kpiAmount;

	/** 시작날짜. */
	private Date kpiStartDate;

	/** 끝나는 날. */
	private Date kpiEndDate;

	/** 매장테이블. */
	private Shop shop;

	/** kpi구분. */
	private Kpidivision kpidivision;

	/**
	 * 생성자.
	 */
	public Kpi() {
	}

	/**
	 * kpi 코드을 설정합니다..
	 * 
	 * @param kpiCode
	 *            kpi 코드
	 */
	public void setKpiCode(Integer kpiCode) {
		this.kpiCode = kpiCode;
	}

	/**
	 * kpi 코드을 가져옵니다..
	 * 
	 * @return kpi 코드
	 */
	public Integer getKpiCode() {
		return this.kpiCode;
	}

	/**
	 * 액수을 설정합니다..
	 * 
	 * @param kpiAmount
	 *            액수
	 */
	public void setKpiAmount(Integer kpiAmount) {
		this.kpiAmount = kpiAmount;
	}

	/**
	 * 액수을 가져옵니다..
	 * 
	 * @return 액수
	 */
	public Integer getKpiAmount() {
		return this.kpiAmount;
	}

	/**
	 * 시작날짜을 설정합니다..
	 * 
	 * @param kpiStartDate
	 *            시작날짜
	 */
	public void setKpiStartDate(Date kpiStartDate) {
		this.kpiStartDate = kpiStartDate;
	}

	/**
	 * 시작날짜을 가져옵니다..
	 * 
	 * @return 시작날짜
	 */
	public Date getKpiStartDate() {
		return this.kpiStartDate;
	}

	/**
	 * 끝나는 날을 설정합니다..
	 * 
	 * @param kpiEndDate
	 *            끝나는 날
	 */
	public void setKpiEndDate(Date kpiEndDate) {
		this.kpiEndDate = kpiEndDate;
	}

	/**
	 * 끝나는 날을 가져옵니다..
	 * 
	 * @return 끝나는 날
	 */
	public Date getKpiEndDate() {
		return this.kpiEndDate;
	}

	/**
	 * 매장테이블을 설정합니다..
	 * 
	 * @param shop
	 *            매장테이블
	 */
	public void setShop(Shop shop) {
		this.shop = shop;
	}

	/**
	 * 매장테이블을 가져옵니다..
	 * 
	 * @return 매장테이블
	 */
	public Shop getShop() {
		return this.shop;
	}

	/**
	 * kpi구분을 설정합니다..
	 * 
	 * @param kpidivision
	 *            kpi구분
	 */
	public void setKpidivision(Kpidivision kpidivision) {
		this.kpidivision = kpidivision;
	}

	/**
	 * kpi구분을 가져옵니다..
	 * 
	 * @return kpi구분
	 */
	public Kpidivision getKpidivision() {
		return this.kpidivision;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((kpiCode == null) ? 0 : kpiCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Kpi other = (Kpi) obj;
		if (kpiCode == null) {
			if (other.kpiCode != null) {
				return false;
			}
		} else if (!kpiCode.equals(other.kpiCode)) {
			return false;
		}
		return true;
	}

}
