package com.kilha.www.vo;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * kpi구분 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Kpidivision implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 구분코드. */
	private Integer kpidivisionCode;

	/** 구분명. */
	private String kpidivisionName;

	/** KPI테이블 목록. */
	private Set<Kpi> kpiSet;

	/**
	 * 생성자.
	 */
	public Kpidivision() {
		this.kpiSet = new HashSet<Kpi>();
	}

	/**
	 * 구분코드을 설정합니다..
	 * 
	 * @param kpidivisionCode
	 *            구분코드
	 */
	public void setKpidivisionCode(Integer kpidivisionCode) {
		this.kpidivisionCode = kpidivisionCode;
	}

	/**
	 * 구분코드을 가져옵니다..
	 * 
	 * @return 구분코드
	 */
	public Integer getKpidivisionCode() {
		return this.kpidivisionCode;
	}

	/**
	 * 구분명을 설정합니다..
	 * 
	 * @param kpidivisionName
	 *            구분명
	 */
	public void setKpidivisionName(String kpidivisionName) {
		this.kpidivisionName = kpidivisionName;
	}

	/**
	 * 구분명을 가져옵니다..
	 * 
	 * @return 구분명
	 */
	public String getKpidivisionName() {
		return this.kpidivisionName;
	}

	/**
	 * KPI테이블 목록을 설정합니다..
	 * 
	 * @param kpiSet
	 *            KPI테이블 목록
	 */
	public void setKpiSet(Set<Kpi> kpiSet) {
		this.kpiSet = kpiSet;
	}

	/**
	 * KPI테이블를 추가합니다..
	 * 
	 * @param kpi
	 *            KPI테이블
	 */
	public void addKpi(Kpi kpi) {
		this.kpiSet.add(kpi);
	}

	/**
	 * KPI테이블 목록을 가져옵니다..
	 * 
	 * @return KPI테이블 목록
	 */
	public Set<Kpi> getKpiSet() {
		return this.kpiSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((kpidivisionCode == null) ? 0 : kpidivisionCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Kpidivision other = (Kpidivision) obj;
		if (kpidivisionCode == null) {
			if (other.kpidivisionCode != null) {
				return false;
			}
		} else if (!kpidivisionCode.equals(other.kpidivisionCode)) {
			return false;
		}
		return true;
	}

}
