package com.kilha.www.vo;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 영업프로세스테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Process implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 프로세스 코드. */
	private String processCode;

	/** 입력날짜. */
	private Date processInsertDate;

	/** 유효기간. */
	private Date processTerm;

	/** 납품 종료일. */
	private Date processEndDate;

	/** 종결여부. */
	private Integer processState;

	/** 매장테이블. */
	private Shop shop;

	/** 직원테이블. */
	private Staff staff;

	/** 창고 테이블. */
	private Warehouse warehouse;

	/** 납품목록테이블 목록. */
	private Set<Supply> supplySet;

	/**
	 * 생성자.
	 */
	public Process() {
		this.supplySet = new HashSet<Supply>();
	}

	/**
	 * 프로세스 코드을 설정합니다..
	 * 
	 * @param processCode
	 *            프로세스 코드
	 */
	public void setProcessCode(String processCode) {
		this.processCode = processCode;
	}

	/**
	 * 프로세스 코드을 가져옵니다..
	 * 
	 * @return 프로세스 코드
	 */
	public String getProcessCode() {
		return this.processCode;
	}

	/**
	 * 입력날짜을 설정합니다..
	 * 
	 * @param processInsertDate
	 *            입력날짜
	 */
	public void setProcessInsertDate(Date processInsertDate) {
		this.processInsertDate = processInsertDate;
	}

	/**
	 * 입력날짜을 가져옵니다..
	 * 
	 * @return 입력날짜
	 */
	public Date getProcessInsertDate() {
		return this.processInsertDate;
	}

	/**
	 * 유효기간을 설정합니다..
	 * 
	 * @param processTerm
	 *            유효기간
	 */
	public void setProcessTerm(Date processTerm) {
		this.processTerm = processTerm;
	}

	/**
	 * 유효기간을 가져옵니다..
	 * 
	 * @return 유효기간
	 */
	public Date getProcessTerm() {
		return this.processTerm;
	}

	/**
	 * 납품 종료일을 설정합니다..
	 * 
	 * @param processEndDate
	 *            납품 종료일
	 */
	public void setProcessEndDate(Date processEndDate) {
		this.processEndDate = processEndDate;
	}

	/**
	 * 납품 종료일을 가져옵니다..
	 * 
	 * @return 납품 종료일
	 */
	public Date getProcessEndDate() {
		return this.processEndDate;
	}

	/**
	 * 종결여부을 설정합니다..
	 * 
	 * @param processState
	 *            종결여부
	 */
	public void setProcessState(Integer processState) {
		this.processState = processState;
	}

	/**
	 * 종결여부을 가져옵니다..
	 * 
	 * @return 종결여부
	 */
	public Integer getProcessState() {
		return this.processState;
	}

	/**
	 * 매장테이블을 설정합니다..
	 * 
	 * @param shop
	 *            매장테이블
	 */
	public void setShop(Shop shop) {
		this.shop = shop;
	}

	/**
	 * 매장테이블을 가져옵니다..
	 * 
	 * @return 매장테이블
	 */
	public Shop getShop() {
		return this.shop;
	}

	/**
	 * 직원테이블을 설정합니다..
	 * 
	 * @param staff
	 *            직원테이블
	 */
	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	/**
	 * 직원테이블을 가져옵니다..
	 * 
	 * @return 직원테이블
	 */
	public Staff getStaff() {
		return this.staff;
	}

	/**
	 * 창고 테이블을 설정합니다..
	 * 
	 * @param warehouse
	 *            창고 테이블
	 */
	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	/**
	 * 창고 테이블을 가져옵니다..
	 * 
	 * @return 창고 테이블
	 */
	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	/**
	 * 납품목록테이블 목록을 설정합니다..
	 * 
	 * @param supplySet
	 *            납품목록테이블 목록
	 */
	public void setSupplySet(Set<Supply> supplySet) {
		this.supplySet = supplySet;
	}

	/**
	 * 납품목록테이블를 추가합니다..
	 * 
	 * @param supply
	 *            납품목록테이블
	 */
	public void addSupply(Supply supply) {
		this.supplySet.add(supply);
	}

	/**
	 * 납품목록테이블 목록을 가져옵니다..
	 * 
	 * @return 납품목록테이블 목록
	 */
	public Set<Supply> getSupplySet() {
		return this.supplySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((processCode == null) ? 0 : processCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Process other = (Process) obj;
		if (processCode == null) {
			if (other.processCode != null) {
				return false;
			}
		} else if (!processCode.equals(other.processCode)) {
			return false;
		}
		return true;
	}

}
