package com.kilha.www.vo;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 상품테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 상품 코드. */
	private String productCode;

	/** 상품명. */
	private String productName;

	/** 입고단가. */
	private Integer productUnitPrice;

	/** 출고단가. */
	private Integer productReleasePrice;

	/** 상품이미지. */
	private String productImage;

	/** 단위. */
	private String productUnit;

	/** 판매가. */
	private Integer productSalesPrice;

	/** 경쟁사 납품 정보 테이블 목록. */
	private Set<Competitorsupply> competitorsupplySet;

	/** 납품목록테이블 목록. */
	private Set<Supply> supplySet;

	/**
	 * 생성자.
	 */
	public Product() {
		this.competitorsupplySet = new HashSet<Competitorsupply>();
		this.supplySet = new HashSet<Supply>();
	}

	/**
	 * 상품 코드을 설정합니다..
	 * 
	 * @param productCode
	 *            상품 코드
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	 * 상품 코드을 가져옵니다..
	 * 
	 * @return 상품 코드
	 */
	public String getProductCode() {
		return this.productCode;
	}

	/**
	 * 상품명을 설정합니다..
	 * 
	 * @param productName
	 *            상품명
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * 상품명을 가져옵니다..
	 * 
	 * @return 상품명
	 */
	public String getProductName() {
		return this.productName;
	}

	/**
	 * 입고단가을 설정합니다..
	 * 
	 * @param productUnitPrice
	 *            입고단가
	 */
	public void setProductUnitPrice(Integer productUnitPrice) {
		this.productUnitPrice = productUnitPrice;
	}

	/**
	 * 입고단가을 가져옵니다..
	 * 
	 * @return 입고단가
	 */
	public Integer getProductUnitPrice() {
		return this.productUnitPrice;
	}

	/**
	 * 출고단가을 설정합니다..
	 * 
	 * @param productReleasePrice
	 *            출고단가
	 */
	public void setProductReleasePrice(Integer productReleasePrice) {
		this.productReleasePrice = productReleasePrice;
	}

	/**
	 * 출고단가을 가져옵니다..
	 * 
	 * @return 출고단가
	 */
	public Integer getProductReleasePrice() {
		return this.productReleasePrice;
	}

	/**
	 * 상품이미지을 설정합니다..
	 * 
	 * @param productImage
	 *            상품이미지
	 */
	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	/**
	 * 상품이미지을 가져옵니다..
	 * 
	 * @return 상품이미지
	 */
	public String getProductImage() {
		return this.productImage;
	}

	/**
	 * 단위을 설정합니다..
	 * 
	 * @param productUnit
	 *            단위
	 */
	public void setProductUnit(String productUnit) {
		this.productUnit = productUnit;
	}

	/**
	 * 단위을 가져옵니다..
	 * 
	 * @return 단위
	 */
	public String getProductUnit() {
		return this.productUnit;
	}

	/**
	 * 판매가을 설정합니다..
	 * 
	 * @param productSalesPrice
	 *            판매가
	 */
	public void setProductSalesPrice(Integer productSalesPrice) {
		this.productSalesPrice = productSalesPrice;
	}

	/**
	 * 판매가을 가져옵니다..
	 * 
	 * @return 판매가
	 */
	public Integer getProductSalesPrice() {
		return this.productSalesPrice;
	}

	/**
	 * 경쟁사 납품 정보 테이블 목록을 설정합니다..
	 * 
	 * @param competitorsupplySet
	 *            경쟁사 납품 정보 테이블 목록
	 */
	public void setCompetitorsupplySet(Set<Competitorsupply> competitorsupplySet) {
		this.competitorsupplySet = competitorsupplySet;
	}

	/**
	 * 경쟁사 납품 정보 테이블를 추가합니다..
	 * 
	 * @param competitorsupply
	 *            경쟁사 납품 정보 테이블
	 */
	public void addCompetitorsupply(Competitorsupply competitorsupply) {
		this.competitorsupplySet.add(competitorsupply);
	}

	/**
	 * 경쟁사 납품 정보 테이블 목록을 가져옵니다..
	 * 
	 * @return 경쟁사 납품 정보 테이블 목록
	 */
	public Set<Competitorsupply> getCompetitorsupplySet() {
		return this.competitorsupplySet;
	}

	/**
	 * 납품목록테이블 목록을 설정합니다..
	 * 
	 * @param supplySet
	 *            납품목록테이블 목록
	 */
	public void setSupplySet(Set<Supply> supplySet) {
		this.supplySet = supplySet;
	}

	/**
	 * 납품목록테이블를 추가합니다..
	 * 
	 * @param supply
	 *            납품목록테이블
	 */
	public void addSupply(Supply supply) {
		this.supplySet.add(supply);
	}

	/**
	 * 납품목록테이블 목록을 가져옵니다..
	 * 
	 * @return 납품목록테이블 목록
	 */
	public Set<Supply> getSupplySet() {
		return this.supplySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productCode == null) ? 0 : productCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (productCode == null) {
			if (other.productCode != null) {
				return false;
			}
		} else if (!productCode.equals(other.productCode)) {
			return false;
		}
		return true;
	}

}
