package com.kilha.www.vo;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * 매장테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Shop implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 매장코드. */
	private Integer shopCode;

	/** 매장명. */
	private String shopName;

	/** 사업자등록번호. */
	private String shopNumber;

	/** 대표자명. */
	private String shopRep;

	/** 전화번호. */
	private String shopTel;

	/** 매장 상태 테이블. */
	private String shopState;

	/** 경쟁사 납품 정보 테이블 목록. */
	/*private Set<Competitorsupply> competitorsupplySet;

	*//** 영업프로세스테이블 목록. *//*
	private Set<Process> processSet;
*/
	/** 주소 테이블 목록. */
	private List<Address> addressSet;

	/** KPI테이블 목록. *//*
	private Set<Kpi> kpiSet;
*/
	/**
	 * 생성자.
	 */
	public Shop() {
		this.addressSet = new ArrayList<Address>();
		/*this.competitorsupplySet = new HashSet<Competitorsupply>();
		this.kpiSet = new HashSet<Kpi>();
		this.processSet = new HashSet<Process>();*/
	}

	/**
	 * 매장코드을 설정합니다..
	 * 
	 * @param shopCode
	 *            매장코드
	 */
	public void setShopCode(Integer shopCode) {
		this.shopCode = shopCode;
	}

	/**
	 * 매장코드을 가져옵니다..
	 * 
	 * @return 매장코드
	 */
	public Integer getShopCode() {
		return this.shopCode;
	}

	/**
	 * 매장명을 설정합니다..
	 * 
	 * @param shopName
	 *            매장명
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	/**
	 * 매장명을 가져옵니다..
	 * 
	 * @return 매장명
	 */
	public String getShopName() {
		return this.shopName;
	}
	
	public String getShopState() {
		return shopState;
	}

	public void setShopState(String shopState) {
		this.shopState = shopState;
	}

	/**
	 * 사업자등록번호을 설정합니다..
	 * 
	 * @param shopNumber
	 *            사업자등록번호
	 */
	public void setShopNumber(String shopNumber) {
		this.shopNumber = shopNumber;
	}

	/**
	 * 사업자등록번호을 가져옵니다..
	 * 
	 * @return 사업자등록번호
	 */
	public String getShopNumber() {
		return this.shopNumber;
	}

	/**
	 * 대표자명을 설정합니다..
	 * 
	 * @param shopRep
	 *            대표자명
	 */
	public void setShopRep(String shopRep) {
		this.shopRep = shopRep;
	}

	/**
	 * 대표자명을 가져옵니다..
	 * 
	 * @return 대표자명
	 */
	public String getShopRep() {
		return this.shopRep;
	}

	/**
	 * 전화번호을 설정합니다..
	 * 
	 * @param shopTel
	 *            전화번호
	 */
	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

	/**
	 * 전화번호을 가져옵니다..
	 * 
	 * @return 전화번호
	 */
	public String getShopTel() {
		return this.shopTel;
	}

	/**
	 * 경쟁사 납품 정보 테이블 목록을 설정합니다..
	 * 
	 * @param competitorsupplySet
	 *            경쟁사 납품 정보 테이블 목록
	 */
	/*public void setCompetitorsupplySet(Set<Competitorsupply> competitorsupplySet) {
		this.competitorsupplySet = competitorsupplySet;
	}

	*//**
	 * 경쟁사 납품 정보 테이블를 추가합니다..
	 * 
	 * @param competitorsupply
	 *            경쟁사 납품 정보 테이블
	 *//*
	public void addCompetitorsupply(Competitorsupply competitorsupply) {
		this.competitorsupplySet.add(competitorsupply);
	}

	*//**
	 * 경쟁사 납품 정보 테이블 목록을 가져옵니다..
	 * 
	 * @return 경쟁사 납품 정보 테이블 목록
	 *//*
	public Set<Competitorsupply> getCompetitorsupplySet() {
		return this.competitorsupplySet;
	}

	*//**
	 * 영업프로세스테이블 목록을 설정합니다..
	 * 
	 * @param processSet
	 *            영업프로세스테이블 목록
	 *//*
	public void setProcessSet(Set<Process> processSet) {
		this.processSet = processSet;
	}

	*//**
	 * 영업프로세스테이블를 추가합니다..
	 * 
	 * @param process
	 *            영업프로세스테이블
	 *//*
	public void addProcess(Process process) {
		this.processSet.add(process);
	}

	*//**
	 * 영업프로세스테이블 목록을 가져옵니다..
	 * 
	 * @return 영업프로세스테이블 목록
	 *//*
	public Set<Process> getProcessSet() {
		return this.processSet;
	}*/


	/**
	 * KPI테이블 목록을 설정합니다..
	 * 
	 * @param kpiSet
	 *            KPI테이블 목록
	 */
	/*public void setKpiSet(Set<Kpi> kpiSet) {
		this.kpiSet = kpiSet;
	}

	*//**
	 * KPI테이블를 추가합니다..
	 * 
	 * @param kpi
	 *            KPI테이블
	 *//*
	public void addKpi(Kpi kpi) {
		this.kpiSet.add(kpi);
	}

	*//**
	 * KPI테이블 목록을 가져옵니다..
	 * 
	 * @return KPI테이블 목록
	 *//*
	public Set<Kpi> getKpiSet() {
		return this.kpiSet;
	}*/

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((shopCode == null) ? 0 : shopCode.hashCode());
		return result;
	}

	public List<Address> getAddressSet() {
		return addressSet;
	}

	public void setAddressSet(List<Address> addressSet) {
		this.addressSet = addressSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Shop other = (Shop) obj;
		if (shopCode == null) {
			if (other.shopCode != null) {
				return false;
			}
		} else if (!shopCode.equals(other.shopCode)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Shop [shopCode=" + shopCode + ", shopName=" + shopName + ", shopNumber=" + shopNumber + ", shopRep="
				+ shopRep + ", shopTel=" + shopTel + ", shopState=" + shopState + ", addressSet=" + addressSet + "]";
	}

}
