package com.kilha.www.vo;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 직원테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Staff implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 직원코드. */
	private Short staffCode;

	/** 직원이름. */
	private String staffName;
	
	private String staffDepartment;

	/** 영업프로세스테이블 목록. */
	private Set<Process> processSet;

	/**
	 * 생성자.
	 */
	public Staff() {
		this.processSet = new HashSet<Process>();
	}

	/**
	 * 직원코드을 설정합니다..
	 * 
	 * @param staffCode
	 *            직원코드
	 */
	public void setStaffCode(Short staffCode) {
		this.staffCode = staffCode;
	}

	/**
	 * 직원코드을 가져옵니다..
	 * 
	 * @return 직원코드
	 */
	public Short getStaffCode() {
		return this.staffCode;
	}

	/**
	 * 직원이름을 설정합니다..
	 * 
	 * @param staffName
	 *            직원이름
	 */
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	/**
	 * 직원이름을 가져옵니다..
	 * 
	 * @return 직원이름
	 */
	public String getStaffName() {
		return this.staffName;
	}
	
	public String getStaffDepartment() {
		return staffDepartment;
	}

	public void setStaffDepartment(String staffDepartment) {
		this.staffDepartment = staffDepartment;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * 영업프로세스테이블 목록을 설정합니다..
	 * 
	 * @param processSet
	 *            영업프로세스테이블 목록
	 */
	public void setProcessSet(Set<Process> processSet) {
		this.processSet = processSet;
	}

	/**
	 * 영업프로세스테이블를 추가합니다..
	 * 
	 * @param process
	 *            영업프로세스테이블
	 */
	public void addProcess(Process process) {
		this.processSet.add(process);
	}

	/**
	 * 영업프로세스테이블 목록을 가져옵니다..
	 * 
	 * @return 영업프로세스테이블 목록
	 */
	public Set<Process> getProcessSet() {
		return this.processSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((staffCode == null) ? 0 : staffCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Staff other = (Staff) obj;
		if (staffCode == null) {
			if (other.staffCode != null) {
				return false;
			}
		} else if (!staffCode.equals(other.staffCode)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Staff [staffCode=" + staffCode + ", staffName=" + staffName + ", staffDepartment=" + staffDepartment
				+ ", processSet=" + processSet + "]";
	}

}
