package com.kilha.www.vo;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 매장 상태 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class State implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 상태코드. */
	private Integer stateCode;

	/** 상태명. */
	private String stateName;

	/** 매장테이블 목록. */
	private Set<Shop> shopSet;

	/**
	 * 생성자.
	 */
	public State() {
		this.shopSet = new HashSet<Shop>();
	}

	/**
	 * 상태코드을 설정합니다..
	 * 
	 * @param stateCode
	 *            상태코드
	 */
	public void setStateCode(Integer stateCode) {
		this.stateCode = stateCode;
	}

	/**
	 * 상태코드을 가져옵니다..
	 * 
	 * @return 상태코드
	 */
	public Integer getStateCode() {
		return this.stateCode;
	}

	/**
	 * 상태명을 설정합니다..
	 * 
	 * @param stateName
	 *            상태명
	 */
	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	/**
	 * 상태명을 가져옵니다..
	 * 
	 * @return 상태명
	 */
	public String getStateName() {
		return this.stateName;
	}

	/**
	 * 매장테이블 목록을 설정합니다..
	 * 
	 * @param shopSet
	 *            매장테이블 목록
	 */
	public void setShopSet(Set<Shop> shopSet) {
		this.shopSet = shopSet;
	}

	/**
	 * 매장테이블를 추가합니다..
	 * 
	 * @param shop
	 *            매장테이블
	 */
	public void addShop(Shop shop) {
		this.shopSet.add(shop);
	}

	/**
	 * 매장테이블 목록을 가져옵니다..
	 * 
	 * @return 매장테이블 목록
	 */
	public Set<Shop> getShopSet() {
		return this.shopSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((stateCode == null) ? 0 : stateCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		State other = (State) obj;
		if (stateCode == null) {
			if (other.stateCode != null) {
				return false;
			}
		} else if (!stateCode.equals(other.stateCode)) {
			return false;
		}
		return true;
	}

}
