package com.kilha.www.vo;
import java.io.Serializable;

/**
 * 납품목록테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Supply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 상품테이블. */
	private Product product;

	/** 영업프로세스테이블. */
	private Process process;

	/** 수량. */
	private Integer supplyVolume;

	/** 납품가격. */
	private Integer supplyPrice;

	/**
	 * 생성자.
	 */
	public Supply() {
	}

	/**
	 * 상품테이블을 설정합니다..
	 * 
	 * @param product
	 *            상품테이블
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * 상품테이블을 가져옵니다..
	 * 
	 * @return 상품테이블
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * 영업프로세스테이블을 설정합니다..
	 * 
	 * @param process
	 *            영업프로세스테이블
	 */
	public void setProcess(Process process) {
		this.process = process;
	}

	/**
	 * 영업프로세스테이블을 가져옵니다..
	 * 
	 * @return 영업프로세스테이블
	 */
	public Process getProcess() {
		return this.process;
	}

	/**
	 * 수량을 설정합니다..
	 * 
	 * @param supplyVolume
	 *            수량
	 */
	public void setSupplyVolume(Integer supplyVolume) {
		this.supplyVolume = supplyVolume;
	}

	/**
	 * 수량을 가져옵니다..
	 * 
	 * @return 수량
	 */
	public Integer getSupplyVolume() {
		return this.supplyVolume;
	}

	/**
	 * 납품가격을 설정합니다..
	 * 
	 * @param supplyPrice
	 *            납품가격
	 */
	public void setSupplyPrice(Integer supplyPrice) {
		this.supplyPrice = supplyPrice;
	}

	/**
	 * 납품가격을 가져옵니다..
	 * 
	 * @return 납품가격
	 */
	public Integer getSupplyPrice() {
		return this.supplyPrice;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((product == null) ? 0 : product.hashCode());
		result = prime * result + ((process == null) ? 0 : process.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Supply other = (Supply) obj;
		if (product == null) {
			if (other.product != null) {
				return false;
			}
		} else if (!product.equals(other.product)) {
			return false;
		}
		if (process == null) {
			if (other.process != null) {
				return false;
			}
		} else if (!process.equals(other.process)) {
			return false;
		}
		return true;
	}

}
