package com.kilha.www.vo;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 창고 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Warehouse implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 창고코드. */
	private String warehouseCode;

	/** 창고명. */
	private String warehouseName;

	/** 창고종류. */
	private Integer warehouseType;

	/** 영업프로세스테이블 목록. */
	private Set<Process> processSet;

	/**
	 * 생성자.
	 */
	public Warehouse() {
		this.processSet = new HashSet<Process>();
	}

	/**
	 * 창고코드을 설정합니다..
	 * 
	 * @param warehouseCode
	 *            창고코드
	 */
	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode;
	}

	/**
	 * 창고코드을 가져옵니다..
	 * 
	 * @return 창고코드
	 */
	public String getWarehouseCode() {
		return this.warehouseCode;
	}

	/**
	 * 창고명을 설정합니다..
	 * 
	 * @param warehouseName
	 *            창고명
	 */
	public void setWarehouseName(String warehouseName) {
		this.warehouseName = warehouseName;
	}

	/**
	 * 창고명을 가져옵니다..
	 * 
	 * @return 창고명
	 */
	public String getWarehouseName() {
		return this.warehouseName;
	}

	/**
	 * 창고종류을 설정합니다..
	 * 
	 * @param warehouseType
	 *            창고종류
	 */
	public void setWarehouseType(Integer warehouseType) {
		this.warehouseType = warehouseType;
	}

	/**
	 * 창고종류을 가져옵니다..
	 * 
	 * @return 창고종류
	 */
	public Integer getWarehouseType() {
		return this.warehouseType;
	}

	/**
	 * 영업프로세스테이블 목록을 설정합니다..
	 * 
	 * @param processSet
	 *            영업프로세스테이블 목록
	 */
	public void setProcessSet(Set<Process> processSet) {
		this.processSet = processSet;
	}

	/**
	 * 영업프로세스테이블를 추가합니다..
	 * 
	 * @param process
	 *            영업프로세스테이블
	 */
	public void addProcess(Process process) {
		this.processSet.add(process);
	}

	/**
	 * 영업프로세스테이블 목록을 가져옵니다..
	 * 
	 * @return 영업프로세스테이블 목록
	 */
	public Set<Process> getProcessSet() {
		return this.processSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((warehouseCode == null) ? 0 : warehouseCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Warehouse other = (Warehouse) obj;
		if (warehouseCode == null) {
			if (other.warehouseCode != null) {
				return false;
			}
		} else if (!warehouseCode.equals(other.warehouseCode)) {
			return false;
		}
		return true;
	}

}
