package com.kilha.www.vo.sal;
import java.io.Serializable;

/**
 * �ּ� ���̺� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Address implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** �����ȣ. */
	private String addressPost;

	/** ��, �� ����. */
	private String addressDetail1;

	/** ��, �� ����. */
	private String addressDetail2;

	/** ����, ���θ� �ּ�. */
	private String addressDetail3;

	/** ������ ���ּ�. */
	private String addressDetail4;
	
	/** �����ڵ�. */
	private Integer shopCode;
	
	/**
	 * ������.
	 */
	public Address() {
	}

	/**
	 * �����ȣ�� �����մϴ�..
	 * 
	 * @param addressPost
	 *            �����ȣ
	 */
	public void setAddressPost(String addressPost) {
		this.addressPost = addressPost;
	}

	/**
	 * �����ȣ�� �����ɴϴ�..
	 * 
	 * @return �����ȣ
	 */
	public String getAddressPost() {
		return this.addressPost;
	}

	/**
	 * ��, �� ������ �����մϴ�..
	 * 
	 * @param addressDetail1
	 *            ��, �� ����
	 */
	public void setAddressDetail1(String addressDetail1) {
		this.addressDetail1 = addressDetail1;
	}

	/**
	 * ��, �� ������ �����ɴϴ�..
	 * 
	 * @return ��, �� ����
	 */
	public String getAddressDetail1() {
		return this.addressDetail1;
	}

	/**
	 * ��, �� ������ �����մϴ�..
	 * 
	 * @param addressDetail2
	 *            ��, �� ����
	 */
	public void setAddressDetail2(String addressDetail2) {
		this.addressDetail2 = addressDetail2;
	}

	/**
	 * ��, �� ������ �����ɴϴ�..
	 * 
	 * @return ��, �� ����
	 */
	public String getAddressDetail2() {
		return this.addressDetail2;
	}

	/**
	 * ����, ���θ� �ּ��� �����մϴ�..
	 * 
	 * @param addressDetail3
	 *            ����, ���θ� �ּ�
	 */
	public void setAddressDetail3(String addressDetail3) {
		this.addressDetail3 = addressDetail3;
	}

	/**
	 * ����, ���θ� �ּ��� �����ɴϴ�..
	 * 
	 * @return ����, ���θ� �ּ�
	 */
	public String getAddressDetail3() {
		return this.addressDetail3;
	}

	/**
	 * ������ ���ּ��� �����մϴ�..
	 * 
	 * @param addressDetail4
	 *            ������ ���ּ�
	 */
	public void setAddressDetail4(String addressDetail4) {
		this.addressDetail4 = addressDetail4;
	}

	/**
	 * ������ ���ּ��� �����ɴϴ�..
	 * 
	 * @return ������ ���ּ�
	 */
	public String getAddressDetail4() {
		return this.addressDetail4;
	}


	public Integer getShopCode() {
		return shopCode;
	}

	public void setShopCode(Integer shopCode) {
		this.shopCode = shopCode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addressPost == null) ? 0 : addressPost.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Address other = (Address) obj;
		if (addressPost == null) {
			if (other.addressPost != null) {
				return false;
			}
		} else if (!addressPost.equals(other.addressPost)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Address [addressPost=" + addressPost + ", addressDetail1=" + addressDetail1 + ", addressDetail2="
				+ addressDetail2 + ", addressDetail3=" + addressDetail3 + ", addressDetail4=" + addressDetail4
				+ ", shopCode=" + shopCode + "]";
	}
	
	
}
