package com.kilha.www.vo.sal;
import java.io.Serializable;
import java.util.Date;

/**
 * KPI���̺� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Kpi implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** kpi �ڵ�. */
	private Integer kpiCode;

	/** �׼�. */
	private Integer kpiAmount;

	/** ���۳�¥. */
	private Date kpiStartDate;

	/** ������ ��. */
	private Date kpiEndDate;

	/** �������̺�. */
	private Shop shop;

	/** kpi����. */
	private Kpidivision kpidivision;

	/**
	 * ������.
	 */
	public Kpi() {
	}

	/**
	 * kpi �ڵ��� �����մϴ�..
	 * 
	 * @param kpiCode
	 *            kpi �ڵ�
	 */
	public void setKpiCode(Integer kpiCode) {
		this.kpiCode = kpiCode;
	}

	/**
	 * kpi �ڵ��� �����ɴϴ�..
	 * 
	 * @return kpi �ڵ�
	 */
	public Integer getKpiCode() {
		return this.kpiCode;
	}

	/**
	 * �׼��� �����մϴ�..
	 * 
	 * @param kpiAmount
	 *            �׼�
	 */
	public void setKpiAmount(Integer kpiAmount) {
		this.kpiAmount = kpiAmount;
	}

	/**
	 * �׼��� �����ɴϴ�..
	 * 
	 * @return �׼�
	 */
	public Integer getKpiAmount() {
		return this.kpiAmount;
	}

	/**
	 * ���۳�¥�� �����մϴ�..
	 * 
	 * @param kpiStartDate
	 *            ���۳�¥
	 */
	public void setKpiStartDate(Date kpiStartDate) {
		this.kpiStartDate = kpiStartDate;
	}

	/**
	 * ���۳�¥�� �����ɴϴ�..
	 * 
	 * @return ���۳�¥
	 */
	public Date getKpiStartDate() {
		return this.kpiStartDate;
	}

	/**
	 * ������ ���� �����մϴ�..
	 * 
	 * @param kpiEndDate
	 *            ������ ��
	 */
	public void setKpiEndDate(Date kpiEndDate) {
		this.kpiEndDate = kpiEndDate;
	}

	/**
	 * ������ ���� �����ɴϴ�..
	 * 
	 * @return ������ ��
	 */
	public Date getKpiEndDate() {
		return this.kpiEndDate;
	}

	/**
	 * �������̺��� �����մϴ�..
	 * 
	 * @param shop
	 *            �������̺�
	 */
	public void setShop(Shop shop) {
		this.shop = shop;
	}

	/**
	 * �������̺��� �����ɴϴ�..
	 * 
	 * @return �������̺�
	 */
	public Shop getShop() {
		return this.shop;
	}

	/**
	 * kpi������ �����մϴ�..
	 * 
	 * @param kpidivision
	 *            kpi����
	 */
	public void setKpidivision(Kpidivision kpidivision) {
		this.kpidivision = kpidivision;
	}

	/**
	 * kpi������ �����ɴϴ�..
	 * 
	 * @return kpi����
	 */
	public Kpidivision getKpidivision() {
		return this.kpidivision;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((kpiCode == null) ? 0 : kpiCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Kpi other = (Kpi) obj;
		if (kpiCode == null) {
			if (other.kpiCode != null) {
				return false;
			}
		} else if (!kpiCode.equals(other.kpiCode)) {
			return false;
		}
		return true;
	}

}
