package com.kilha.www.vo.sal;
import java.io.Serializable;
import java.util.Date;

/**
 * KPI���̺� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Kpi implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** kpi �ڵ�. */
	private Integer kpiCode;

	/** �׼�. */
	private long kpiAmount;

	/** ���۳�¥. */
	private Date kpiStartDate;

	/** ������ ��. */
	private Date kpiEndDate;

	/** �������̺�. */
	private int shopCode;

	public Kpi() {
		super();
	}

	public Integer getKpiCode() {
		return kpiCode;
	}

	public void setKpiCode(Integer kpiCode) {
		this.kpiCode = kpiCode;
	}

	public long getKpiAmount() {
		return kpiAmount;
	}

	public void setKpiAmount(long kpiAmount) {
		this.kpiAmount = kpiAmount;
	}

	public Date getKpiStartDate() {
		return kpiStartDate;
	}

	public void setKpiStartDate(Date kpiStartDate) {
		this.kpiStartDate = kpiStartDate;
	}

	public Date getKpiEndDate() {
		return kpiEndDate;
	}

	public void setKpiEndDate(Date kpiEndDate) {
		this.kpiEndDate = kpiEndDate;
	}

	public int getShopCode() {
		return shopCode;
	}

	public void setShopCode(int shopCode) {
		this.shopCode = shopCode;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (kpiAmount ^ (kpiAmount >>> 32));
		result = prime * result + ((kpiCode == null) ? 0 : kpiCode.hashCode());
		result = prime * result + ((kpiEndDate == null) ? 0 : kpiEndDate.hashCode());
		result = prime * result + ((kpiStartDate == null) ? 0 : kpiStartDate.hashCode());
		result = prime * result + shopCode;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Kpi other = (Kpi) obj;
		if (kpiAmount != other.kpiAmount)
			return false;
		if (kpiCode == null) {
			if (other.kpiCode != null)
				return false;
		} else if (!kpiCode.equals(other.kpiCode))
			return false;
		if (kpiEndDate == null) {
			if (other.kpiEndDate != null)
				return false;
		} else if (!kpiEndDate.equals(other.kpiEndDate))
			return false;
		if (kpiStartDate == null) {
			if (other.kpiStartDate != null)
				return false;
		} else if (!kpiStartDate.equals(other.kpiStartDate))
			return false;
		if (shopCode != other.shopCode)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Kpi [kpiCode=" + kpiCode + ", kpiAmount=" + kpiAmount + ", kpiStartDate=" + kpiStartDate
				+ ", kpiEndDate=" + kpiEndDate + ", shopCode=" + shopCode + "]";
	}



}
