package com.kilha.www.vo.sal;
import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * kpi���� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Kpidivision implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** �����ڵ�. */
	private Integer kpidivisionCode;

	/** ���и�. */
	private String kpidivisionName;

	/** KPI���̺� ���. */
	private List<Kpi> kpiSet;

	public Kpidivision() {
		super();
	}

	public Integer getKpidivisionCode() {
		return kpidivisionCode;
	}

	public void setKpidivisionCode(Integer kpidivisionCode) {
		this.kpidivisionCode = kpidivisionCode;
	}

	public String getKpidivisionName() {
		return kpidivisionName;
	}

	public void setKpidivisionName(String kpidivisionName) {
		this.kpidivisionName = kpidivisionName;
	}

	public List<Kpi> getKpiSet() {
		return kpiSet;
	}

	public void setKpiSet(List<Kpi> kpiSet) {
		this.kpiSet = kpiSet;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((kpiSet == null) ? 0 : kpiSet.hashCode());
		result = prime * result + ((kpidivisionCode == null) ? 0 : kpidivisionCode.hashCode());
		result = prime * result + ((kpidivisionName == null) ? 0 : kpidivisionName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Kpidivision other = (Kpidivision) obj;
		if (kpiSet == null) {
			if (other.kpiSet != null)
				return false;
		} else if (!kpiSet.equals(other.kpiSet))
			return false;
		if (kpidivisionCode == null) {
			if (other.kpidivisionCode != null)
				return false;
		} else if (!kpidivisionCode.equals(other.kpidivisionCode))
			return false;
		if (kpidivisionName == null) {
			if (other.kpidivisionName != null)
				return false;
		} else if (!kpidivisionName.equals(other.kpidivisionName))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Kpidivision [kpidivisionCode=" + kpidivisionCode + ", kpidivisionName=" + kpidivisionName + ", kpiSet="
				+ kpiSet + "]";
	}

	
}
