package com.kilha.www.vo.sal;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * �������̺� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Shop implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** �����ڵ�. */
	private Integer shopCode;

	/** �����. */
	private String shopName;

	/** ����ڵ�Ϲ�ȣ. */
	private String shopNumber;

	/** ��ǥ�ڸ�. */
	private String shopRep;

	/** ��ȭ��ȣ. */
	private String shopTel;

	/** ���� ���� ���̺�. */
	private String shopState;
	
	private String shopEmail;
	
	private String shopSNS;

	private List<Address> addressSet;

	public Shop() {
		super();
	}

	public Integer getShopCode() {
		return shopCode;
	}

	public void setShopCode(Integer shopCode) {
		this.shopCode = shopCode;
	}

	public String getShopName() {
		return shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getShopNumber() {
		return shopNumber;
	}

	public void setShopNumber(String shopNumber) {
		this.shopNumber = shopNumber;
	}

	public String getShopRep() {
		return shopRep;
	}

	public void setShopRep(String shopRep) {
		this.shopRep = shopRep;
	}

	public String getShopTel() {
		return shopTel;
	}

	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

	public String getShopState() {
		return shopState;
	}

	public void setShopState(String shopState) {
		this.shopState = shopState;
	}

	public String getShopEmail() {
		return shopEmail;
	}

	public void setShopEmail(String shopEmail) {
		this.shopEmail = shopEmail;
	}

	public String getShopSNS() {
		return shopSNS;
	}

	public void setShopSNS(String shopSNS) {
		this.shopSNS = shopSNS;
	}

	public List<Address> getAddressSet() {
		return addressSet;
	}

	public void setAddressSet(List<Address> addressSet) {
		this.addressSet = addressSet;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addressSet == null) ? 0 : addressSet.hashCode());
		result = prime * result + ((shopCode == null) ? 0 : shopCode.hashCode());
		result = prime * result + ((shopEmail == null) ? 0 : shopEmail.hashCode());
		result = prime * result + ((shopName == null) ? 0 : shopName.hashCode());
		result = prime * result + ((shopNumber == null) ? 0 : shopNumber.hashCode());
		result = prime * result + ((shopRep == null) ? 0 : shopRep.hashCode());
		result = prime * result + ((shopSNS == null) ? 0 : shopSNS.hashCode());
		result = prime * result + ((shopState == null) ? 0 : shopState.hashCode());
		result = prime * result + ((shopTel == null) ? 0 : shopTel.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Shop other = (Shop) obj;
		if (addressSet == null) {
			if (other.addressSet != null)
				return false;
		} else if (!addressSet.equals(other.addressSet))
			return false;
		if (shopCode == null) {
			if (other.shopCode != null)
				return false;
		} else if (!shopCode.equals(other.shopCode))
			return false;
		if (shopEmail == null) {
			if (other.shopEmail != null)
				return false;
		} else if (!shopEmail.equals(other.shopEmail))
			return false;
		if (shopName == null) {
			if (other.shopName != null)
				return false;
		} else if (!shopName.equals(other.shopName))
			return false;
		if (shopNumber == null) {
			if (other.shopNumber != null)
				return false;
		} else if (!shopNumber.equals(other.shopNumber))
			return false;
		if (shopRep == null) {
			if (other.shopRep != null)
				return false;
		} else if (!shopRep.equals(other.shopRep))
			return false;
		if (shopSNS == null) {
			if (other.shopSNS != null)
				return false;
		} else if (!shopSNS.equals(other.shopSNS))
			return false;
		if (shopState == null) {
			if (other.shopState != null)
				return false;
		} else if (!shopState.equals(other.shopState))
			return false;
		if (shopTel == null) {
			if (other.shopTel != null)
				return false;
		} else if (!shopTel.equals(other.shopTel))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Shop [shopCode=" + shopCode + ", shopName=" + shopName + ", shopNumber=" + shopNumber + ", shopRep="
				+ shopRep + ", shopTel=" + shopTel + ", shopState=" + shopState + ", shopEmail=" + shopEmail
				+ ", shopSNS=" + shopSNS + ", addressSet=" + addressSet + "]";
	}

}
