package com.kilha.www.vo.sal;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * �������̺� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Shop implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** �����ڵ�. */
	private Integer shopCode;

	/** �����. */
	private String shopName;

	/** ����ڵ�Ϲ�ȣ. */
	private String shopNumber;

	/** ��ǥ�ڸ�. */
	private String shopRep;

	/** ��ȭ��ȣ. */
	private String shopTel;

	/** ���� ���� ���̺�. */
	private String shopState;

	/** ����� ��ǰ ���� ���̺� ���. */
	/*private Set<Competitorsupply> competitorsupplySet;

	*//** �������μ������̺� ���. *//*
	private Set<Process> processSet;
*/
	/** �ּ� ���̺� ���. */
	private List<Address> addressSet;

	/** KPI���̺� ���. *//*
	private Set<Kpi> kpiSet;
*/
	/**
	 * ������.
	 */
	public Shop() {
		this.addressSet = new ArrayList<Address>();
		/*this.competitorsupplySet = new HashSet<Competitorsupply>();
		this.kpiSet = new HashSet<Kpi>();
		this.processSet = new HashSet<Process>();*/
	}

	/**
	 * �����ڵ��� �����մϴ�..
	 * 
	 * @param shopCode
	 *            �����ڵ�
	 */
	public void setShopCode(Integer shopCode) {
		this.shopCode = shopCode;
	}

	/**
	 * �����ڵ��� �����ɴϴ�..
	 * 
	 * @return �����ڵ�
	 */
	public Integer getShopCode() {
		return this.shopCode;
	}

	/**
	 * ������� �����մϴ�..
	 * 
	 * @param shopName
	 *            �����
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	/**
	 * ������� �����ɴϴ�..
	 * 
	 * @return �����
	 */
	public String getShopName() {
		return this.shopName;
	}
	
	public String getShopState() {
		return shopState;
	}

	public void setShopState(String shopState) {
		this.shopState = shopState;
	}

	/**
	 * ����ڵ�Ϲ�ȣ�� �����մϴ�..
	 * 
	 * @param shopNumber
	 *            ����ڵ�Ϲ�ȣ
	 */
	public void setShopNumber(String shopNumber) {
		this.shopNumber = shopNumber;
	}

	/**
	 * ����ڵ�Ϲ�ȣ�� �����ɴϴ�..
	 * 
	 * @return ����ڵ�Ϲ�ȣ
	 */
	public String getShopNumber() {
		return this.shopNumber;
	}

	/**
	 * ��ǥ�ڸ��� �����մϴ�..
	 * 
	 * @param shopRep
	 *            ��ǥ�ڸ�
	 */
	public void setShopRep(String shopRep) {
		this.shopRep = shopRep;
	}

	/**
	 * ��ǥ�ڸ��� �����ɴϴ�..
	 * 
	 * @return ��ǥ�ڸ�
	 */
	public String getShopRep() {
		return this.shopRep;
	}

	/**
	 * ��ȭ��ȣ�� �����մϴ�..
	 * 
	 * @param shopTel
	 *            ��ȭ��ȣ
	 */
	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

	/**
	 * ��ȭ��ȣ�� �����ɴϴ�..
	 * 
	 * @return ��ȭ��ȣ
	 */
	public String getShopTel() {
		return this.shopTel;
	}

	/**
	 * ����� ��ǰ ���� ���̺� ����� �����մϴ�..
	 * 
	 * @param competitorsupplySet
	 *            ����� ��ǰ ���� ���̺� ���
	 */
	/*public void setCompetitorsupplySet(Set<Competitorsupply> competitorsupplySet) {
		this.competitorsupplySet = competitorsupplySet;
	}

	*//**
	 * ����� ��ǰ ���� ���̺� �߰��մϴ�..
	 * 
	 * @param competitorsupply
	 *            ����� ��ǰ ���� ���̺�
	 *//*
	public void addCompetitorsupply(Competitorsupply competitorsupply) {
		this.competitorsupplySet.add(competitorsupply);
	}

	*//**
	 * ����� ��ǰ ���� ���̺� ����� �����ɴϴ�..
	 * 
	 * @return ����� ��ǰ ���� ���̺� ���
	 *//*
	public Set<Competitorsupply> getCompetitorsupplySet() {
		return this.competitorsupplySet;
	}

	*//**
	 * �������μ������̺� ����� �����մϴ�..
	 * 
	 * @param processSet
	 *            �������μ������̺� ���
	 *//*
	public void setProcessSet(Set<Process> processSet) {
		this.processSet = processSet;
	}

	*//**
	 * �������μ������̺� �߰��մϴ�..
	 * 
	 * @param process
	 *            �������μ������̺�
	 *//*
	public void addProcess(Process process) {
		this.processSet.add(process);
	}

	*//**
	 * �������μ������̺� ����� �����ɴϴ�..
	 * 
	 * @return �������μ������̺� ���
	 *//*
	public Set<Process> getProcessSet() {
		return this.processSet;
	}*/


	/**
	 * KPI���̺� ����� �����մϴ�..
	 * 
	 * @param kpiSet
	 *            KPI���̺� ���
	 */
	/*public void setKpiSet(Set<Kpi> kpiSet) {
		this.kpiSet = kpiSet;
	}

	*//**
	 * KPI���̺� �߰��մϴ�..
	 * 
	 * @param kpi
	 *            KPI���̺�
	 *//*
	public void addKpi(Kpi kpi) {
		this.kpiSet.add(kpi);
	}

	*//**
	 * KPI���̺� ����� �����ɴϴ�..
	 * 
	 * @return KPI���̺� ���
	 *//*
	public Set<Kpi> getKpiSet() {
		return this.kpiSet;
	}*/

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((shopCode == null) ? 0 : shopCode.hashCode());
		return result;
	}

	public List<Address> getAddressSet() {
		return addressSet;
	}

	public void setAddressSet(List<Address> addressSet) {
		this.addressSet = addressSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Shop other = (Shop) obj;
		if (shopCode == null) {
			if (other.shopCode != null) {
				return false;
			}
		} else if (!shopCode.equals(other.shopCode)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Shop [shopCode=" + shopCode + ", shopName=" + shopName + ", shopNumber=" + shopNumber + ", shopRep="
				+ shopRep + ", shopTel=" + shopTel + ", shopState=" + shopState + ", addressSet=" + addressSet + "]";
	}

}
