package com.kilha.www.vo.common;
import java.io.Serializable;

/**
 * ��ǰ���̺� �� Ŭ����.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ��ǰ �ڵ�. */
	private String productCode;

	/** ��ǰ��. */
	private String productName;

	/** �԰�ܰ�. */
	private Integer productUnitPrice;

	/** ���ܰ�. */
	private Integer productReleasePrice;

	/** ��ǰ�̹���. */
	private String productImage;

	/** ����. */
	private String productUnit;

	/** �ǸŰ�. */
	private Integer productSalesPrice;

	/**
	 * ��ǰ �ڵ��� �����մϴ�..
	 * 
	 * @param productCode
	 *            ��ǰ �ڵ�
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	 * ��ǰ �ڵ��� �����ɴϴ�..
	 * 
	 * @return ��ǰ �ڵ�
	 */
	public String getProductCode() {
		return this.productCode;
	}

	/**
	 * ��ǰ���� �����մϴ�..
	 * 
	 * @param productName
	 *            ��ǰ��
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * ��ǰ���� �����ɴϴ�..
	 * 
	 * @return ��ǰ��
	 */
	public String getProductName() {
		return this.productName;
	}

	/**
	 * �԰�ܰ��� �����մϴ�..
	 * 
	 * @param productUnitPrice
	 *            �԰�ܰ�
	 */
	public void setProductUnitPrice(Integer productUnitPrice) {
		this.productUnitPrice = productUnitPrice;
	}

	/**
	 * �԰�ܰ��� �����ɴϴ�..
	 * 
	 * @return �԰�ܰ�
	 */
	public Integer getProductUnitPrice() {
		return this.productUnitPrice;
	}

	/**
	 * ���ܰ��� �����մϴ�..
	 * 
	 * @param productReleasePrice
	 *            ���ܰ�
	 */
	public void setProductReleasePrice(Integer productReleasePrice) {
		this.productReleasePrice = productReleasePrice;
	}

	/**
	 * ���ܰ��� �����ɴϴ�..
	 * 
	 * @return ���ܰ�
	 */
	public Integer getProductReleasePrice() {
		return this.productReleasePrice;
	}

	/**
	 * ��ǰ�̹����� �����մϴ�..
	 * 
	 * @param productImage
	 *            ��ǰ�̹���
	 */
	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	/**
	 * ��ǰ�̹����� �����ɴϴ�..
	 * 
	 * @return ��ǰ�̹���
	 */
	public String getProductImage() {
		return this.productImage;
	}

	/**
	 * ������ �����մϴ�..
	 * 
	 * @param productUnit
	 *            ����
	 */
	public void setProductUnit(String productUnit) {
		this.productUnit = productUnit;
	}

	/**
	 * ������ �����ɴϴ�..
	 * 
	 * @return ����
	 */
	public String getProductUnit() {
		return this.productUnit;
	}

	/**
	 * �ǸŰ��� �����մϴ�..
	 * 
	 * @param productSalesPrice
	 *            �ǸŰ�
	 */
	public void setProductSalesPrice(Integer productSalesPrice) {
		this.productSalesPrice = productSalesPrice;
	}

	/**
	 * �ǸŰ��� �����ɴϴ�..
	 * 
	 * @return �ǸŰ�
	 */
	public Integer getProductSalesPrice() {
		return this.productSalesPrice;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productCode == null) ? 0 : productCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (productCode == null) {
			if (other.productCode != null) {
				return false;
			}
		} else if (!productCode.equals(other.productCode)) {
			return false;
		}
		return true;
	}

}
